"""All survey question data, hardcoded from Questionnaire.docx."""

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _mc(qid, label, a, b, c, d):
    return {
        'id': qid,
        'label': label,
        'type': 'radio',
        'options': [f'A. {a}', f'B. {b}', f'C. {c}', f'D. {d}'],
        'required': True,
    }


def _sa(qid, label):
    return {'id': qid, 'label': label, 'type': 'textarea', 'required': True}


def _heading(label):
    return {'id': f'_h_{label[:8]}', 'type': 'heading', 'label': label}


# ---------------------------------------------------------------------------
# Learning Outcome definitions
# ---------------------------------------------------------------------------

_LO_STATEMENTS = {
    'LO1': 'LO1 — Binary & reverse engineering: The CTF challenges helped me understand how to interpret binary executables, read disassembly output, and reason about program logic.',
    'LO2': 'LO2 — Output-based symbolic execution: I learned how to use symbolic execution (e.g., angr) to find inputs that satisfy a program\'s success condition based on runtime output rather than specific addresses.',
    'LO3': 'LO3 — Stack manipulation: I can now calculate stack padding, manage stack frames, and place symbolic values at the correct offsets when performing binary analysis.',
    'LO4': 'LO4 — Start address selection: I understand why choosing the correct start address for symbolic execution matters, and I can identify an appropriate one from a binary.',
    'LO5': 'LO5 — Dynamic memory simulation: I learned how to simulate dynamic memory allocation by creating fake heap addresses and injecting symbolic values into memory regions.',
    'LO6': 'LO6 — Symbolic file system creation: I can create symbolic file systems in angr and simulate file-reading operations using tools like SimFile to replace real file input.',
    'LO7': 'LO7 — Constraint-based solving: I learned how to apply constraints manually in angr to solve challenges when full symbolic execution becomes too complex due to excessive branching.',
    'LO8': 'LO8 — Function hooking & state explosion management: I can use angr hooks (including SimProcedure) to bypass computationally intensive functions and manage state explosion in symbolic execution.',
}


def _lo_section(lo_ids):
    statements = [
        {'id': f'lo_{lo_id.lower()}', 'text': _LO_STATEMENTS[lo_id]}
        for lo_id in lo_ids
    ]
    return {
        'id': 'lo',
        'title': 'Learning Outcomes',
        'description': 'Rate how much you agree with each statement about what you learned from this challenge.',
        'questions': [
            {
                'id': 'lo_ratings',
                'type': 'likert_group',
                'label': 'Rate each statement (1 = Strongly Disagree, 5 = Strongly Agree):',
                'statements': statements,
            },
        ],
    }


_LIKERT_SECTION = {
    'id': 'b2',
    'title': 'B2 · Hint Quality Rating',
    'description': '⚠️ Only complete this section if you requested hints during this challenge.',
    'questions': [
        {
            'id': 'b2_hints',
            'type': 'likert_group',
            'label': 'Rate each statement  (1 = Strongly Disagree, 5 = Strongly Agree):',
            'statements': [
                {'id': 'b2_s1', 'text': '1. The hint was relevant to the specific point where I was stuck.'},
                {'id': 'b2_s2', 'text': '2. The hint helped me move forward without revealing the answer directly.'},
                {'id': 'b2_s3', 'text': '3. I understood the reasoning behind why the hint was pointing me in that direction.'},
            ],
        },
        {
            'id': 'b2_helpful_description',
            'label': 'Q4b. In your own words, how did the hint(s) help you? What specifically was useful?',
            'type': 'textarea',
            'required': False,
        },
        {
            'id': 'b2_feedback',
            'label': 'Q5. If any hint was confusing, unhelpful, or too revealing, briefly describe what was wrong with it:',
            'type': 'textarea',
            'required': False,
        },
    ],
}

# ---------------------------------------------------------------------------
# Pre-Study Survey
# ---------------------------------------------------------------------------

_PRE_STUDY_A1 = {
    'id': 'a1',
    'title': 'Section A1 · Demographic & Prior Experience Survey',
    'questions': [
        {'id': 'participant_id', 'label': 'Participant ID', 'type': 'text', 'required': True},
        {'id': 'age', 'label': 'Age', 'type': 'text', 'required': False},
        {
            'id': 'year',
            'label': 'Year in Program',
            'type': 'radio',
            'options': ['1st', '2nd', '3rd', '4th', 'Graduate'],
            'required': False,
        },
        {
            'id': 'course',
            'label': 'Course',
            'type': 'radio',
            'options': ['CS 492', 'CS 592'],
            'required': False,
        },
        {'id': 'gender', 'label': 'Gender (optional)', 'type': 'text', 'required': False},
        _heading('B. CTF & Security Experience'),
        {
            'id': 'a1_q1',
            'label': '1. How many CTF challenges have you completed prior to this course?',
            'type': 'radio',
            'options': ['None', '1–5', '6–15', '16–30', 'More than 30'],
            'required': True,
        },
        {
            'id': 'a1_q2',
            'label': '2. Rate your overall cybersecurity knowledge before this course:',
            'type': 'radio',
            'options': ['Beginner', 'Basic', 'Intermediate', 'Advanced', 'Expert'],
            'required': True,
        },
        {
            'id': 'a1_q3',
            'label': '3. Have you used angr or any symbolic execution tool before?',
            'type': 'radio',
            'options': ['Yes', 'No', 'Heard of it but never used it'],
            'required': True,
        },
        {
            'id': 'a1_q4',
            'label': '4. Rate your comfort with x86 assembly / binary reverse engineering:',
            'type': 'radio',
            'options': ['None', 'Minimal', 'Moderate', 'Comfortable', 'Very comfortable'],
            'required': True,
        },
        _heading('C. Programming Background'),
        {
            'id': 'a1_q5',
            'label': '5. Years of programming experience:',
            'type': 'radio',
            'options': ['< 1 year', '1–2 years', '2–3 years', '3+ years'],
            'required': True,
        },
        {
            'id': 'a1_q6',
            'label': '6. Comfort level with Python:',
            'type': 'radio',
            'options': ['Not comfortable', 'Somewhat', 'Comfortable', 'Very comfortable'],
            'required': True,
        },
        _heading('D. Prior AI Tool Use'),
        {
            'id': 'a1_q7',
            'label': '7. How often do you use AI tools (ChatGPT, Copilot, etc.) for coursework?',
            'type': 'radio',
            'options': ['Never', 'Rarely (few times/semester)', 'Sometimes (weekly)', 'Often (daily)'],
            'required': True,
        },
        {
            'id': 'a1_q8',
            'label': '8. When stuck on a problem, what do you do first?  (Select all that apply)',
            'type': 'checkbox',
            'options': [
                'Search the web / documentation',
                'Ask LLM (e.g. GPT, Claude, etc)',
                'Ask a classmate or instructor',
                'Re-read lecture slides',
                'Try independently for a while first',
            ],
            'required': False,
        },
        {
            'id': 'a1_q9',
            'label': '9. How much do you trust AI-generated answers for technical security questions?',
            'type': 'radio',
            'options': ['Not at all', 'Slightly', 'Moderately', 'Mostly', 'Completely'],
            'required': True,
        },
    ],
}

_PRE_STUDY_A2 = {
    'id': 'a2',
    'title': 'Section A2 · FORM A — Pre-Study Knowledge Test',
    'description': '⚑ Complete BEFORE any CTF challenge. Do NOT use any external resources. Estimated time: 12–15 minutes.',
    'questions': [
        _heading('Part I — Multiple Choice  (Questions 1–10) — Select the single best answer.'),
        _mc('a2_q1',
            'Q1. What does symbolic execution do that concrete (normal) execution does not?',
            'Runs the program faster by skipping complex functions',
            'Represents inputs as symbolic variables and explores all possible execution paths simultaneously by tracking constraints',
            'Automatically patches memory vulnerabilities found in a binary',
            'Disassembles a binary into human-readable assembly code'),
        _mc('a2_q2',
            'Q2. In angr, what is a SimulationManager primarily used for?',
            "Storing a knowledge graph of the binary's call structure",
            'Managing and stepping through multiple symbolic execution states simultaneously during exploration',
            'Compiling Python solution scripts into native binary format',
            'Monitoring CPU usage and memory consumption during analysis'),
        _mc('a2_q3',
            'Q3. What is the difference between a concrete bitvector and a symbolic bitvector in angr/claripy?',
            'A concrete bitvector holds exactly one value; a symbolic bitvector can represent multiple possible values constrained by path conditions',
            'A concrete bitvector is used for strings; a symbolic bitvector is used for integers only',
            'A concrete bitvector is faster to compute; a symbolic one is more accurate',
            'There is no meaningful difference — the terms are interchangeable in claripy'),
        _mc('a2_q4',
            'Q4. What is path explosion in symbolic execution?',
            'A bug that causes angr to consume all available RAM regardless of input',
            'An exponential increase in the number of active execution states when branch conditions multiply across loops or complex conditionals',
            "The process of extracting all function addresses from a binary's symbol table",
            'An error produced when a bitvector constraint is unsatisfiable'),
        _mc('a2_q5',
            'Q5. Which of the following correctly describes the purpose of the avoid parameter in simulation.explore()?',
            'It marks addresses where angr should inject symbolic values automatically',
            'It specifies execution paths or states that angr should terminate immediately and discard, pruning the search space',
            'It sets a maximum number of steps before exploration halts',
            'It defines the starting address for symbolic execution'),
        _mc('a2_q6',
            'Q6. When would you use project.factory.blank_state() instead of project.factory.entry_state()?',
            'When you want to begin execution at the very start of main()',
            'When you need to start execution at an arbitrary mid-program address, bypassing earlier code such as a complex input routine',
            'When you want angr to automatically inject symbols at stdin',
            'When the binary is statically linked and has no external library dependencies'),
        _mc('a2_q7',
            'Q7. What does solver.eval(symbolic_var, cast_to=bytes) return?',
            'Converts a concrete integer into a new symbolic bitvector',
            'Produces a concrete byte value that satisfies all accumulated constraints on the symbolic variable',
            'Adds a new constraint requiring the variable to equal a specific byte sequence',
            'Checks whether a bitvector is satisfiable without producing any concrete value'),
        _mc('a2_q8',
            'Q8. What is the primary reason to use a hook (@project.hook or hook_symbol) in angr?',
            'To speed up exploration by parallelizing execution across CPU cores',
            'To replace a function or instruction with custom Python logic, bypassing complex, unsupported, or adversarial code',
            'To inject a new branch condition into the binary at runtime',
            'To export the constraint system to an external solver'),
        _mc('a2_q9',
            'Q9. When injecting symbolic values onto the stack for a function mid-execution, why must you carefully set both %ebp and %esp?',
            'angr requires stack frames to be 16-byte aligned for all x86 architectures without exception',
            'Local variables are accessed via offsets from %ebp (e.g., [ebp-0xc]); incorrect %ebp placement causes angr to read symbolic values from wrong memory locations, corrupting the simulation',
            "angr's blank_state() initializes %ebp == %esp and they must never diverge",
            '%esp is only required when the function makes calls to other functions'),
        _mc('a2_q10',
            "Q10. Why do angr's built-in SimProcedures for libc functions (like printf, scanf) not apply automatically to statically linked binaries?",
            'Static binaries use a different instruction set than dynamically linked ones',
            'In dynamic binaries, angr hooks functions at PLT stubs by symbol name; in static binaries, libc is compiled directly in and symbols may not be present, so angr cannot identify which code corresponds to which function',
            'Static binaries encrypt their function tables, preventing angr from reading them',
            'angr does not support ELF format for statically linked binaries at all'),
        _heading('Part II — Short Answer  (Questions 11–12) — Answer in your own words, 3–5 sentences.'),
        _sa('a2_q11',
            'Q11. Explain in your own words what constraint propagation is in symbolic execution and why it is useful for solving CTF challenges.'),
        _sa('a2_q12',
            'Q12. What is the key difference between using simulation.explore(find=0x804867a) versus simulation.explore(find=is_successful) where is_successful is a function? When would you choose one over the other?'),
    ],
}

PRE_STUDY = {
    'id': 'pre_study',
    'label': 'Pre-Study',
    'title': 'Pre-Study Survey',
    'description': 'Complete this packet before your first CTF session. Estimated time: 15–20 minutes.',
    'sections': [_PRE_STUDY_A1, _PRE_STUDY_A2],
}

# ---------------------------------------------------------------------------
# Post-Challenge Surveys
# ---------------------------------------------------------------------------

def _challenge(num_str, name, core_concept, b1_questions, lo_ids=None):
    sections = [
        {
            'id': 'meta',
            'title': f'Challenge {num_str} · {name}',
            'questions': [
                {'id': 'core_concept_display', 'type': 'display',
                 'label': 'Core Concept', 'value': core_concept},
                {
                    'id': 'completed',
                    'label': 'Completed?',
                    'type': 'radio',
                    'options': ['Yes, fully', 'Partially', 'Did not complete'],
                    'required': True,
                },
                {'id': 'time_spent', 'label': 'Time spent (minutes)', 'type': 'number', 'required': True},
            ],
        },
        {
            'id': 'b1',
            'title': 'B1 · Post-Challenge Knowledge Test',
            'description': 'Answer from memory. Do not look anything up.',
            'questions': b1_questions,
        },
        _LIKERT_SECTION,
    ]
    if lo_ids:
        sections.append(_lo_section(lo_ids))
    return {
        'id': f'ctf_{num_str}',
        'label': f'CTF {num_str}',
        'title': f'CTF {num_str} — Post-Challenge Survey',
        'challenge_name': name,
        'core_concept': core_concept,
        'description': 'Complete immediately after finishing the challenge. Estimated time: 5–8 minutes.',
        'sections': sections,
    }


CHALLENGES = [
    _challenge('00', '00_angr_find', 'Basic angr exploration using a target memory address', [
        _mc('b1_q1',
            'Q1. In 00_angr_find, why does adding complex_function to the binary NOT prevent angr from solving it quickly?',
            'angr automatically detects and skips functions with more than 100 instructions',
            'Symbolic execution reasons about constraints mathematically rather than executing each instruction concretely, so function complexity does not scale execution time proportionally',
            "complex_function is automatically hooked by angr's built-in SimProcedure library",
            'angr patches the binary at runtime to remove complex_function before execution'),
        _mc('b1_q2',
            'Q2. What value should print_good_address hold in scaffold00.py, and where do you find it?',
            "The entry address of main(); found by running 'nm' on the binary",
            "The address of the instruction that prints 'Good Job'; found by disassembling the binary and locating that output call (e.g., 0x804867a)",
            "The address of complex_function's entry point, found in the ELF symbol table",
            'Any arbitrary address — angr searches the entire binary regardless of what you specify'),
        _mc('b1_q3',
            'Q3. What does solution_state.posix.dumps(sys.stdin.fileno()).decode() return after successful exploration?',
            'The memory layout of the binary at the found execution state',
            'The concrete stdin input string that satisfies all path constraints accumulated on the route to print_good_address',
            'A list of all symbolic variable names created during exploration',
            'The stdout output that the program would print at the found state'),
        _sa('b1_q4',
            "Q4. A classmate says: 'I could brute-force all possible inputs instead of using angr.' What specific property of complex_function makes brute-forcing impractical, and how does symbolic execution sidestep this limitation?"),
    ], lo_ids=['LO1']),

    _challenge('01', '01_angr_avoid', 'Pruning failing execution states using the avoid parameter', [
        _mc('b1_q1',
            'Q1. What computational benefit does specifying an avoid address provide over only specifying a find address?',
            'The avoid address tells angr to skip that memory region entirely, reducing binary size in memory',
            'States that reach the avoid address are terminated immediately, preventing angr from spending resources exploring paths that cannot lead to a solution',
            'The avoid address sets a maximum instruction count before halting exploration',
            'There is no real benefit — avoid is cosmetic and does not affect performance'),
        _mc('b1_q2',
            "Q2. A binary prints 'Try Again.' at 0x8048700 and 'Good Job.' at 0x804867a. Which explore() call is correct?",
            'simulation.explore(find=0x8048700, avoid=0x804867a)',
            'simulation.explore(find=0x804867a, avoid=0x8048700)',
            'simulation.explore(avoid=0x804867a)',
            'simulation.explore(find=0x8048700)'),
        _mc('b1_q3',
            'Q3. After successful exploration, simulation.found contains:',
            'A list of all memory addresses visited during the exploration',
            'A list of simulation states that reached the find address, each containing the symbolic input and accumulated constraints',
            'The disassembly of the execution path taken to reach the find address',
            'A single integer representing the number of instructions executed'),
        _sa('b1_q4',
            "Q4. Describe what happens internally to a simulation state when it reaches an avoid address. Why is this behavior critical when analyzing binaries with many 'failure' output branches?"),
    ], lo_ids=['LO1']),

    _challenge('02', '02_angr_find_condition', 'Using Python predicate functions instead of raw addresses for exploration termination', [
        _mc('b1_q1',
            'Q1. Why would you define a function is_successful(state) as the find condition rather than using a raw address?',
            'Python functions are always evaluated faster than address integer comparisons',
            "When the success condition depends on runtime output content (e.g., 'Good Job' appearing in stdout) rather than reaching a fixed address, a function can inspect the state's I/O",
            'Raw addresses only work for 64-bit binaries; functions are required for 32-bit',
            'Functions allow angr to explore all paths simultaneously without any pruning'),
        _mc('b1_q2',
            "Q2. In is_successful, why use 'Good Job'.encode() in stdout_output rather than stdout_output == 'Good Job'.encode()?",
            'encode() converts the string to uppercase before the comparison',
            "The 'in' operator checks for substring presence, handling cases where stdout contains 'Good Job' plus other text; == requires the entire stdout to match exactly",
            '== does not function correctly with bytes objects in Python 3',
            'encode() automatically strips trailing newlines before comparison'),
        _mc('b1_q3',
            'Q3. What Python type does state.posix.dumps(sys.stdout.fileno()) return, and why does this matter?',
            'str — no encoding step is needed before comparison',
            "bytes — any string literals you compare against must also be bytes (e.g., b'Good Job' or 'Good Job'.encode()), otherwise the comparison always returns False",
            'int — you must call chr() on each element to reconstruct the string',
            'list — you must join() the list before any string comparison'),
        _sa('b1_q4',
            "Q4. A binary prints 'ACCESS GRANTED\\n' on success and 'ACCESS DENIED\\n' on failure. Write out the is_successful and should_abort functions (in Python or clear pseudocode) you would use with simulation.explore() for this binary."),
    ], lo_ids=['LO2']),

    _challenge('03', '03_angr_symbolic_registers', 'Manually creating symbolic bitvectors and attaching them to registers', [
        _mc('b1_q1',
            'Q1. Why is it better to start symbolic execution after get_user_input() returns rather than at the start of the program?',
            'angr cannot analyze any function that calls scanf under any circumstances',
            "The input function uses complex format strings that angr's automatic injection cannot efficiently handle; manually injecting symbols after the call avoids symbolically executing the difficult input routine",
            "Starting after the function prevents stack overflow in angr's simulation manager",
            "get_user_input() modifies the binary at runtime, causing angr's disassembler to produce incorrect results"),
        _mc('b1_q2',
            'Q2. If get_user_input() returns three 32-bit passwords via registers eax, ebx, ecx, which claripy call correctly creates one symbolic password?',
            'claripy.BVV(0, 32) — a 32-bit concrete zero value',
            "claripy.BVS('password0', 32) — a 32-bit symbolic bitvector named password0",
            "claripy.BVS('password0', 4) — a 4-bit symbolic bitvector",
            "claripy.Int('password0') — an unbounded integer symbol"),
        _mc('b1_q3',
            'Q3. After exploration, why call solution_state.solver.eval(password0) rather than printing password0 directly?',
            'password0 is a Python string and must be decoded from bytes before printing',
            'password0 is still a symbolic object; solver.eval() produces a concrete integer value that satisfies all the constraints accumulated during exploration',
            'Printing symbolic objects raises an exception in Python 3',
            'solver.eval() is required only for memory-injected symbols, not register-injected ones'),
        _sa('b1_q4',
            "Q4. Explain why the blank_state address you choose must be the instruction immediately after get_user_input() returns — not the first instruction of get_user_input() itself. What goes wrong if you use the function's entry point?"),
    ], lo_ids=['LO1', 'LO4']),

    _challenge('04', '04_angr_symbolic_stack', 'Reconstructing a stack frame and placing symbolic values at correct ebp offsets', [
        _mc('b1_q1',
            'Q1. password0 sits at ebp-0xc and password1 at ebp-0x10. You set %ebp and %esp to the same address and push symbols. Why push password0 before password1?',
            'push is FIFO so the first pushed value is accessed first by the callee',
            'The stack grows downward; pushing password0 first places it at a higher address (ebp-0xc), and the subsequent push of password1 lands at the lower address (ebp-0x10), matching the layout compiled by the program',
            'angr requires pushed symbols to be in alphabetical order',
            'The order does not matter as long as both bitvectors are pushed before exploration begins'),
        _mc('b1_q2',
            'Q2. Why must you set both %ebp and %esp explicitly when using blank_state() inside a function?',
            'blank_state() zeroes all registers, so any unset register causes an immediate crash',
            'Local variables are accessed as offsets from %ebp; if %ebp is wrong, angr reads symbolic values from incorrect addresses. %esp must be set so that push operations place symbols at the exact intended offsets',
            'angr requires %ebp to equal zero in order to enable stack frame analysis mode',
            '%esp is only required when the function will call other nested functions'),
        _mc('b1_q3',
            'Q3. What is the purpose of the padding bytes between %ebp and the first password variable on the stack?',
            'Padding is inserted automatically by angr and can always be ignored',
            'The compiler inserts padding for alignment or to separate the saved frame pointer from local variables; the stack reconstruction must account for this gap so symbols land at the exact offsets from %ebp that the program expects',
            'Padding bytes are symbolic and represent unknown stack content from earlier function calls',
            'Padding only appears in 64-bit binaries and is irrelevant for 32-bit CTF challenges'),
        _sa('b1_q4',
            'Q4. A student tries to solve this challenge by starting execution at the very beginning of handle_user() and letting angr process the stack setup. Describe one specific reason this approach is likely to fail or be extremely slow.'),
    ], lo_ids=['LO1', 'LO3', 'LO4']),

    _challenge('05', '05_angr_symbolic_memory', 'Storing symbolic bitvectors at global memory addresses via initial_state.memory.store()', [
        _mc('b1_q1',
            'Q1. Which angr call places a symbolic bitvector into a specific global memory address?',
            'initial_state.regs.eax = password0',
            'initial_state.memory.store(password0_address, password0)',
            'initial_state.stack.push(password0)',
            'project.hook(password0_address, password0)'),
        _mc('b1_q2',
            'Q2. How do you determine the correct memory addresses for the four password buffers?',
            'Run the binary normally and observe which addresses it prints to stdout',
            'Disassemble the binary to find the addresses of the global buffers passed as arguments to scanf',
            "Use angr's automatic memory mapper to detect buffers dynamically at runtime",
            'The addresses are always 0x1000, 0x2000, 0x3000, 0x4000 for any four-buffer program'),
        _mc('b1_q3',
            'Q3. Why does solution_state.solver.eval(password0, cast_to=bytes) use cast_to=bytes here, whereas the register challenge used plain eval()?',
            'cast_to=bytes converts the symbolic integer to a hex string representation',
            'The password here is a string buffer, not a numeric value; cast_to=bytes instructs the solver to produce a concrete byte sequence satisfying constraints, which can then be decoded to a readable string',
            'cast_to=bytes restricts the solution to printable ASCII characters only',
            'It is functionally identical — cast_to=bytes is just an optional style preference'),
        _sa('b1_q4',
            'Q4. Compare the memory injection in 05_angr_symbolic_memory with the register injection in 03_angr_symbolic_registers. What is fundamentally different about where symbols are stored, and why does that change which angr API calls you use?'),
    ], lo_ids=['LO1', 'LO3']),

    _challenge('06', '06_angr_symbolic_dynamic_memory', "Simulating malloc'd buffers using fixed arbitrary addresses and redirected pointers", [
        _mc('b1_q1',
            "Q1. Why can't you read the heap addresses from the binary's disassembly to inject symbols at the correct malloc'd locations?",
            'objdump does not display heap-related information in its output',
            'Heap addresses are determined at runtime by the memory allocator and are not known statically; they differ on every execution',
            'angr does not support heap memory access in any form',
            "malloc'd regions are always at address 0x0 in angr's simulation environment"),
        _mc('b1_q2',
            'Q2. After fixing symbols at arbitrary heap addresses (e.g., 0x444444 and 0x444454), what additional step is required?',
            'Mark those addresses as non-executable using initial_state.memory.permissions()',
            'Update the pointer variables in the program (e.g., obj.buffer1 at 0xa2def74) to point to your chosen addresses, so that when the program dereferences the pointer, it reads from where you placed the symbols',
            "Call malloc() within angr's simulation to actually allocate the memory regions first",
            'No additional step is needed — angr automatically follows pointers to locate symbolic values'),
        _mc('b1_q3',
            'Q3. Why is a gap of 16 bytes (e.g., 0x444444 and 0x444454) commonly used between fake heap buffers rather than placing them back-to-back?',
            'Heap allocations always have an 8-byte metadata header that must be accounted for in angr',
            'A gap larger than the buffer size ensures the two symbolic regions do not overlap even with minor off-by-one errors in size calculation, making the simulation more robust',
            '0x444454 is the only address angr recognizes as a valid fake heap pointer',
            "The gap must always be a power of 2 due to angr's memory alignment requirements"),
        _sa('b1_q4',
            "Q4. Explain the two-step process for simulating a malloc'd buffer in angr: (1) what you do with an arbitrary address, and (2) what you must do with the original pointer variable in the program. Why are both steps necessary?"),
    ], lo_ids=['LO2', 'LO3', 'LO4', 'LO5']),

    _challenge('07', '07_angr_symbolic_file', "Creating a SimFile with symbolic content and inserting it into angr's simulated filesystem", [
        _mc('b1_q1',
            "Q1. Why can't you use memory.store() to inject the symbol directly into the output buffer in 07_angr_symbolic_file?",
            'memory.store() only operates on stack memory, not buffer memory',
            'The program reads from the file system via fopen()/fread(), not from a direct memory address; angr must intercept the file system call, which requires inserting a SimFile rather than pre-filling the buffer',
            "fread() is not supported by any version of angr's SimProcedure library",
            'The buffer address changes at runtime so you cannot inject at a statically known offset'),
        _mc('b1_q2',
            'Q2. What does angr.storage.SimFile(filename, content=password) do?',
            "Reads an actual file from your host disk into angr's simulation memory",
            "Creates a simulated file object with symbolic content; angr's file system simulation serves this file when the program calls fopen()/fread() on the matching filename",
            'Patches the binary at runtime to redirect fopen() to a different file path',
            'Compresses the symbolic bitvector into a compact file-like representation for storage'),
        _mc('b1_q3',
            'Q3. How do you determine the correct symbolic_file_size_bytes value for the password bitvector?',
            "Always use 64 bytes — that is angr's default file size for all SimFile objects",
            'Examine the fread() call in the disassembly to find its size argument, which tells you exactly how many bytes the program reads from the file',
            'Run the binary and observe how many bytes it requests at runtime via strace',
            'Use an unconstrained size and let angr determine the correct length during exploration'),
        _sa('b1_q4',
            'Q4. Trace the flow of symbolic data in 07_angr_symbolic_file from the point you create the claripy.BVS symbol to the point the solver produces a concrete solution. Name each step and the angr component involved at each stage.'),
    ], lo_ids=['LO4', 'LO6']),

    _challenge('08', '08_angr_constraints', 'Adding explicit equality constraints to bypass character-by-character check functions', [
        _mc('b1_q1',
            'Q1. Why does check_equals_XXX checking the transformed input one character at a time cause path explosion for angr?',
            'angr cannot handle functions with more than 16 conditional branches',
            'Each character comparison creates a fork into two states (match vs. no-match); with 16 characters this creates 2^16 states simultaneously, exhausting memory and exploration time',
            "The character-by-character approach corrupts angr's constraint database",
            "The check function uses x86 instructions that angr's symbolic engine cannot decode"),
        _mc('b1_q2',
            'Q2. The solution stops execution before check_equals and adds a constraint. What does this constraint specify?',
            'That the input register eax must equal a specific integer value before branching',
            "That the transformed buffer in memory (to_check) must equal the target string (e.g., 'BWYRUBQCMVSBRGFU') at the point just before check_equals is called, bypassing the character-by-character branching entirely",
            'That the find address must be reached within 1000 execution steps',
            'That all symbolic variables must be concretized before check_equals executes'),
        _mc('b1_q3',
            'Q3. After adding the constraint, how does the solver produce the final concrete input for stdin?',
            'It reverses the check_equals function mathematically using a lookup table',
            'The constraint system now knows the output of complex_function must be the target string; the solver works backwards through the symbolic transformations to find the input that produces that output',
            'It brute-forces all 8-bit input combinations until one satisfies the single constraint',
            "It reads the answer directly from the binary's initialized data segment"),
        _sa('b1_q4',
            'Q4. Without the constraint, angr explores exponentially many paths through the character-by-character check. Explain in your own words why adding one equality constraint at the right point collapses all those paths into one tractable problem.'),
    ], lo_ids=['LO1', 'LO2', 'LO7']),

    _challenge('09', '09_angr_hooks', 'Replacing a problematic function with a Python hook to intercept symbolic comparisons', [
        _mc('b1_q1',
            'Q1. In 09_angr_hooks, the @project.hook decorator takes a length parameter. What does this length specify?',
            'The maximum number of instructions the hook function itself is allowed to execute',
            'The number of bytes of the original instruction(s) at that address that angr skips after running the hook, effectively replacing those bytes with your Python function',
            'The total byte size of the function being hooked, from entry to return',
            'The number of times this hook will fire during a complete exploration'),
        _mc('b1_q2',
            'Q2. Inside the hook, you load the user input from memory, compare it to the target string, then set state.regs.eax. Why set eax specifically?',
            'eax stores the return address that the caller uses to continue after the hook',
            "By x86 convention, integer return values are passed in eax; setting eax to 1 (true) or 0 (false) mimics what check_equals would have returned, allowing the caller's branch logic to proceed correctly",
            'Setting eax clears all accumulated constraints in the current state, giving a clean slate',
            'eax must be set to a non-zero value to prevent angr from creating a new symbolic variable'),
        _mc('b1_q3',
            'Q3. Compared to the constraint approach in 08_angr_constraints, what does hooking accomplish that adding a constraint does not?',
            "Hooking is faster because it uses native Python instead of angr's constraint engine",
            "Hooking completely replaces the problematic function's execution with efficient Python logic, preventing angr from ever symbolically executing the function's branching code — unlike constraints which still require angr to reach the constraint point",
            'Hooking automatically generates the correct solution without any exploration',
            'There is no meaningful difference — hooks and constraints are interchangeable strategies'),
        _sa('b1_q4',
            'Q4. Compare the strategy in 08 (adding a constraint) with 09 (using a hook). In what type of situation would you prefer hooks over constraints? Provide a concrete example beyond what was covered in these two challenges.'),
    ], lo_ids=['LO7', 'LO8']),

    _challenge('10', '10_angr_simprocedures', 'Using SimProcedure classes for scalable function replacement across many call sites', [
        _mc('b1_q1',
            'Q1. How does a SimProcedure class differ from a simple @project.hook decorator?',
            "SimProcedures run outside angr's symbolic environment using normal concrete Python execution",
            'SimProcedures are defined as classes with a run() method and can be applied to all call sites of a named function at once via hook_symbol, whereas @project.hook targets a single specific address',
            'SimProcedures cannot access symbolic state — they operate only on concrete values',
            'SimProcedures are available only for known libc functions, not user-defined ones'),
        _mc('b1_q2',
            "Q2. Why is project.hook_symbol('check_equals_XXXX', MyProcedure()) more efficient than hooking 256 individual call sites?",
            'hook_symbol compiles the SimProcedure to native code for significantly faster execution',
            'hook_symbol replaces the function at its definition point, covering all 256 call sites with a single registration — you do not need to find and hook each call address individually',
            'hook_symbol automatically parallelizes the 256 invocations across CPU cores',
            'hook_symbol eliminates the need for a find address in the subsequent simulation.explore() call'),
        _mc('b1_q3',
            "Q3. Inside a SimProcedure's run() method, claripy.If(condition, true_bv, false_bv) returns a symbolic value. When is this preferable to a plain Python if/else?",
            'claripy.If is always required inside SimProcedures; Python if/else raises an exception',
            'claripy.If produces a symbolic bitvector that preserves both branches as constraints, allowing the solver to reason about both outcomes; a Python if/else would concretize the condition, losing information about the other branch',
            'Python if/else cannot compare bytes objects, so claripy.If is needed for string comparisons',
            'claripy.If is only needed when the return value is larger than 32 bits'),
        _sa('b1_q4',
            'Q4. Describe a realistic reverse engineering scenario (outside of CTF) where SimProcedures would be essential. What function would you replace, what behavior would your SimProcedure implement, and why would symbolic execution alone be insufficient?'),
    ], lo_ids=['LO8']),

    _challenge('11', '11_angr_sim_scanf', 'Writing a custom SimProcedure to handle multi-format-specifier scanf calls', [
        _mc('b1_q1',
            "Q1. What specific limitation of angr's built-in scanf SimProcedure does 11_angr_sim_scanf expose?",
            "angr's built-in scanf cannot handle integer format specifiers (%d) on 32-bit systems",
            "angr's scanf SimProcedure supports only a single format specifier; when scanf uses multiple specifiers (e.g., '%u %u'), you must write a custom replacement that handles each one",
            "angr's scanf incorrectly modifies the stack frame when called from within a loop",
            "angr's scanf cannot inject symbolic values into memory — only into registers"),
        _mc('b1_q2',
            'Q2. In your custom ReplacementScanf, you store each symbolic bitvector into memory at the address provided as a parameter. Why must you use the endness parameter in memory.store()?',
            'The endness parameter sets the byte order (little-endian vs big-endian) for how the bitvector is stored in simulated memory, matching how the target architecture reads multi-byte values',
            'endness controls whether the store is symbolic or concrete',
            'endness is required to prevent angr from creating duplicate symbolic variables',
            'endness specifies the memory alignment boundary for the store operation'),
        _mc('b1_q3',
            'Q3. After your custom scanf SimProcedure stores symbols and saves them to state.globals, the rest of the solution script is nearly identical to which earlier challenge?',
            'Q9. 09_angr_hooks — you still need to hook check_equals after scanf returns',
            '02_angr_find_condition — define is_successful and should_abort, run explore(), then extract and print the concrete solution from the found state',
            '04_angr_symbolic_stack — you must reconstruct the stack frame after the scanf returns',
            '08_angr_constraints — you must add manual constraints after the scanf SimProcedure runs'),
        _sa('b1_q4',
            "Q4. Why can't you simply skip scanf entirely (by starting execution after it) in 11_angr_sim_scanf the way you bypassed input functions in challenges 03–05? What specific property of this challenge makes that approach fail?"),
    ]),

    _challenge('12', '12_angr_veritesting', 'Enabling automatic state merging to handle loops that cause path explosion', [
        _mc('b1_q1',
            'Q1. Veritesting in angr merges states that diverged at a branch and later converge. Why does this specifically help with loops?',
            'Veritesting converts loops to tail-recursive functions that angr processes natively',
            'Each loop iteration forks states at the branch condition; veritesting merges states that pass through the same loop body, preventing the 2^N state explosion that standard exploration produces',
            'Veritesting detects loops and replaces them with closed-form mathematical expressions',
            'Veritesting removes all branch conditions within loops, making them execute sequentially'),
        _mc('b1_q2',
            'Q2. How do you enable veritesting in angr?',
            'simulation = project.factory.simgr(initial_state, veritesting=True)',
            'simulation.options.add(angr.options.VERITESTING)',
            'project.enable_veritesting()',
            'initial_state.veritesting = True before creating the simulation manager'),
        _mc('b1_q3',
            'Q3. In 12_angr_veritesting, the scaffold is nearly identical to 02_angr_find_condition with one addition. What is that addition?',
            'You must manually specify the loop iteration count as a parameter to explore()',
            'You enable veritesting=True when constructing the simulation manager; the find/avoid functions, state creation, and solution extraction remain identical to 02',
            'You must unroll the loop manually in the scaffold before running exploration',
            "You must provide the binary's loop bounds as a hint using initial_state.add_constraints()"),
        _sa('b1_q4',
            'Q4. Without veritesting, running the 02_angr_find_condition approach on this binary would likely fail or run indefinitely. Using your understanding of how loops create execution states, explain specifically why this happens and how veritesting resolves it.'),
    ]),

    _challenge('13', '13_angr_static_binary', 'Manually hooking libc functions by address when SimProcedures cannot auto-apply', [
        _mc('b1_q1',
            "Q1. Why do angr's built-in SimProcedures for printf and scanf not apply automatically to statically linked binaries?",
            'Static binaries use a different x86 instruction set than dynamically linked executables',
            'In dynamic binaries, angr finds functions via PLT symbol names; in static binaries, libc is compiled directly in and those symbols may be absent, so angr cannot identify which code is printf or scanf',
            'Static binaries encrypt their function dispatch tables to prevent SimProcedure injection',
            'angr does not support the ELF format used by statically linked Linux binaries'),
        _mc('b1_q2',
            "Q2. The solution for 13_angr_static_binary calls project.hook(address, angr.SIM_PROCEDURES['libc']['printf']()). What does the address argument represent here?",
            'The address of the PLT stub for printf, which exists even in static binaries',
            'The concrete address within the statically linked binary where the printf code begins, found by disassembling the binary and identifying which block handles formatted output',
            'Any arbitrary address — angr searches around it to find the nearest printf-like function',
            'The address of the GOT entry for printf, updated at load time'),
        _mc('b1_q3',
            'Q3. When you run objdump -d on a statically linked binary and see thousands of extra functions, what are they?',
            'Debug symbols inserted by the compiler to assist gdb in backtracing',
            'The libc and other library functions compiled and linked directly into the binary, rather than loaded from shared .so files at runtime',
            'angr-generated wrapper stubs for each external call site',
            'Compiler-generated loop unrolling stubs created during optimization'),
        _sa('b1_q4',
            'Q4. A colleague uses the scaffold from level 03 unchanged on this static binary and gets incorrect results. Explain specifically what will fail and what modification is required to make exploration work on a statically linked binary.'),
    ]),

    _challenge('14', '14_angr_shared_library', 'Loading a .so library at a specified base address and symbolically calling its functions', [
        _mc('b1_q1',
            'Q1. In 14_angr_shared_library, the validation logic is in a .so file rather than the main binary. What must you specify when loading the library with angr.Project()?',
            "The library's SHA256 hash so angr can verify integrity before analysis",
            'A custom base address via load_options so angr maps the position-independent library into a known location in the simulated address space, making function addresses predictable',
            "The library's export symbol table as a Python dictionary",
            'Nothing extra — angr automatically detects and maps shared libraries referenced in the ELF header'),
        _mc('b1_q2',
            "Q2. The validate function appears at offset 0x6d7 in objdump output of the .so. Why can't you use 0x6d7 directly as the execution target in angr?",
            'objdump reports byte offsets from the file start, not memory addresses',
            'Shared libraries use position-independent code with a relative base of 0; the actual address is base_address + 0x6d7, where base_address is the address you specified when loading the library',
            'angr subtracts the binary entry point from all addresses automatically',
            "The address is only valid in the dynamic linker's virtual address space, not angr's"),
        _mc('b1_q3',
            'Q3. Why do you use project.factory.call_state(validate_function_address, ...) rather than entry_state() for this challenge?',
            'call_state() is required for all shared library analysis regardless of the function',
            'You are directly calling a specific function in the library rather than starting from the ELF entry point; call_state() sets up a realistic calling convention context with parameters placed correctly',
            'entry_state() does not work when a custom base address is specified',
            'call_state() automatically injects symbolic values into all function parameters'),
        _sa('b1_q4',
            'Q4. Explain the relationship between the main binary and the shared library in this challenge. How does execution flow between them, and why does this require a different angr project setup than all previous challenges?'),
    ]),

    _challenge('15', '15_angr_arbitrary_read', 'Using symbolic execution to find an overflow input that redirects a pointer to a target address', [
        _mc('b1_q1',
            'Q1. In 15_angr_arbitrary_read, the binary uses puts(locals.to_print). How does overflowing the input buffer enable an arbitrary read?',
            'puts() automatically reads from all registers when the format string is overflowed',
            'The input buffer and the to_print pointer are adjacent in memory; overflowing the buffer overwrites the pointer, so puts() dereferences the attacker-controlled address and prints whatever is there',
            'puts() has a format string vulnerability that activates when more than 8 bytes are passed',
            'Overflowing the buffer triggers a signal handler that reads from kernel memory'),
        _mc('b1_q2',
            'Q2. In the check_puts function, you test state.solver.symbolic(puts_parameter). Why check if the parameter is symbolic before adding a constraint?',
            "Concrete pointers cannot be compared to memory addresses in angr's constraint engine",
            'If puts_parameter is concrete, the program has already committed to a fixed address and cannot be redirected; only a symbolic pointer can be constrained to point to good_job',
            "Checking symbolicity is required by angr's API before any memory load operation",
            'A concrete parameter would cause angr to enter an infinite loop when solving'),
        _mc('b1_q3',
            "Q3. Why do you constrain the input to alphanumeric characters in this challenge's ReplacementScanf?",
            'angr cannot generate non-alphanumeric bytes without an additional plugin',
            'The exploit must be typed into a web UI or terminal that may not accept binary bytes; constraining to printable characters ensures the solution is actually usable outside the symbolic environment',
            'Non-alphanumeric bytes cause puts() to terminate early due to null-byte handling',
            'Alphanumeric constraints reduce the solution search space, making exploration faster'),
        _sa('b1_q4',
            'Q4. Describe in plain English (or pseudocode) the complete angr strategy for 15_angr_arbitrary_read, from setting up the symbolic input through the check_puts hook to extracting the final exploit string. Why is a custom puts hook necessary rather than a simple find address?'),
    ]),

    _challenge('16', '16_angr_arbitrary_write', 'Constraining a symbolic pointer to redirect strncpy to an attacker-controlled destination', [
        _mc('b1_q1',
            "Q1. In 16_angr_arbitrary_write, overflowing the input buffer can hijack a strncpy call. What two things must be simultaneously true about strncpy's parameters for the exploit to be possible?",
            'The source pointer must be NULL and the destination buffer must be writable',
            "The destination pointer (to_copy_to) must be symbolic (attacker-controlled) so it can be constrained to point to password_buffer, and the source buffer must be symbolic so it can be constrained to the desired value 'DVTBOGZL'",
            'The length parameter must exceed 32 and the destination must be in the BSS segment',
            'The source buffer must contain only printable ASCII and the destination must be non-executable'),
        _mc('b1_q2',
            'Q2. After confirming both parameters are symbolic, you add two constraints. What does each one specify?',
            "Constraint 1: source equals 'DVTBOGZL'; Constraint 2: destination equals password_buffer's address — together forcing strncpy to write the target string to the password buffer",
            'Constraint 1: length equals 8; Constraint 2: source is not NULL — preventing a segmentation fault',
            'Constraint 1: destination is writable; Constraint 2: source is readable — ensuring memory permissions',
            'Constraint 1: eip equals print_good; Constraint 2: esp is correctly aligned'),
        _mc('b1_q3',
            'Q3. Why does the check_strncpy function hook strncpy rather than using a simpler find=address approach?',
            'Addresses cannot be used as find targets when the binary uses switch statements',
            "The exploit condition (symbolic pointer redirected to password_buffer) can only be detected by inspecting strncpy's parameters at call time; no single fixed address in the binary corresponds to 'the overflow succeeded'",
            'strncpy is not a standard function so angr cannot locate it by address',
            'Hooking strncpy prevents angr from performing the actual copy, which would corrupt the simulation state'),
        _sa('b1_q4',
            'Q4. An arbitrary write primitive lets you write to any address. Describe a specific, concrete exploitation scenario where you would use this capability to achieve code execution. Name the target address you would overwrite and what value you would write there.'),
    ]),

    _challenge('17', '17_angr_arbitrary_jump', 'Finding inputs that overflow a buffer to overwrite the return address and redirect %eip', [
        _mc('b1_q1',
            "Q1. In 17_angr_arbitrary_jump, overflowing read_input's buffer overwrites the saved return address on the stack. What happens at the ret instruction when this occurs?",
            'ret triggers a segmentation fault immediately regardless of what was written',
            'ret pops the (now attacker-controlled) value from the stack into %eip, redirecting execution to whatever address was written there — in this case, print_good',
            'ret detects the corrupted return address and jumps to the exception handler instead',
            'ret is intercepted by the OS and the process is terminated before %eip is loaded'),
        _mc('b1_q2',
            "Q2. Why can't you use simulation.explore(find=print_good_address) directly in this challenge?",
            'angr does not support symbolic execution of ret instructions',
            "When %eip becomes symbolic (unconstrained) due to the overflow, angr moves those states to the 'unconstrained' stash rather than the active one; explore()'s find function cannot be applied to unconstrained states, so you must manually manage the stash",
            'print_good is in a separate shared library that explore() cannot reach',
            'explore() requires a concrete starting address which is unavailable after the overflow'),
        _mc('b1_q3',
            "Q3. You create the symbolic input with at least 100 bytes (claripy.BVS('input', 100*8)) and constrain each byte to be printable ASCII. Why is 100 bytes needed rather than just the 8-byte buffer size?",
            'angr requires all symbolic inputs to be at least 100 bytes for performance reasons',
            'The overflow must extend past the buffer, past any local variables, through any saved registers, and over the saved return address on the stack — 100 bytes ensures the symbolic input is long enough to reach and overwrite %eip',
            '100 bytes matches the default stack frame size for 32-bit x86 programs',
            'Fewer bytes would prevent angr from creating an unconstrained state'),
        _sa('b1_q4',
            "Q4. Reflect on the full progression from 00_angr_find to 17_angr_arbitrary_jump. Identify the single most important conceptual insight you gained about symbolic execution across the entire challenge series. How has your mental model of 'what angr does' changed from the beginning?"),
    ]),
]

# ---------------------------------------------------------------------------
# Post-Study Survey (Form B — after all CTFs complete)
# ---------------------------------------------------------------------------

POST_STUDY = {
    'id': 'post_study',
    'label': 'Post-Study',
    'title': 'Post-Study Knowledge Test — Form B',
    'description': '⚑ Complete AFTER finishing all CTF challenges. Do NOT use any external resources. Estimated time: 12–15 minutes.',
    'sections': [
        {
            'id': 'c1',
            'title': 'Section C1 · FORM B — Post-Study Knowledge Test',
            'description': 'This test uses different questions from Form A but tests the same concepts at the same difficulty level. Your responses allow us to calculate your learning gain across the study.',
            'questions': [
                _heading('Part I — Multiple Choice  (Questions 1–10) — Select the single best answer.'),
                _mc('c1_q1',
                    "Q1. A student says 'I could just run the binary with lots of random inputs.' What does symbolic execution offer that random testing fundamentally cannot?",
                    'Symbolic execution is always faster than running the binary repeatedly',
                    'Symbolic execution treats inputs as mathematical variables and reasons about all possible values at once, guaranteeing coverage of paths that random inputs might never reach',
                    'Symbolic execution patches the binary so it accepts any input',
                    'Symbolic execution eliminates the need to load the binary into memory'),
                _mc('c1_q2',
                    'Q2. After calling simulation.explore(find=0x804867a), what does simulation.found contain if exploration succeeds?',
                    'A list of all memory addresses visited during exploration',
                    'A list of simulation states that reached the find address, each holding the symbolic input and constraints accumulated on that path',
                    'The disassembly listing of the path taken to reach the find address',
                    'A single integer representing the number of steps taken'),
                _mc('c1_q3',
                    "Q3. You call claripy.BVS('password', 32) to create a symbol. Which statement best describes what this object represents at the start of exploration?",
                    'A fixed 32-bit integer with the value zero',
                    'An unconstrained 32-bit symbolic value that can take any value; constraints are added as angr explores paths that depend on it',
                    'A pointer to 32 bytes of memory in the simulated process',
                    'A 32-character ASCII string pre-filled with null bytes'),
                _mc('c1_q4',
                    'Q4. A binary has a loop that runs 32 times, each iteration branching based on whether buffer[i] equals a specific value. Why does this cause path explosion?',
                    "Loops are not supported by angr's symbolic engine",
                    "Each branch doubles the number of active states; after 32 iterations this produces up to 2^32 states — far more than any machine can manage",
                    "The loop overwrites angr's internal constraint table on each iteration",
                    'angr cannot handle integer comparisons inside loops'),
                _mc('c1_q5',
                    "Q5. A binary prints 'Access Denied' at 0x8048700 and 'Access Granted' at 0x804867a. Which explore() call correctly finds the granting input while pruning denial paths?",
                    'simulation.explore(find=0x8048700, avoid=0x804867a)',
                    'simulation.explore(find=0x804867a, avoid=0x8048700)',
                    'simulation.explore(avoid=0x804867a)',
                    'simulation.explore(find=0x8048700)'),
                _mc('c1_q6',
                    "Q6. You are solving a challenge where get_user_input() uses a complex formatted scanf that angr cannot handle automatically. You decide to start execution after the function returns. What is the correct approach?",
                    'Use entry_state() and set a breakpoint at the return address',
                    'Use blank_state(addr=address_after_return) and manually store symbolic bitvectors into the registers or memory locations where get_user_input() would have placed its results',
                    'Use entry_state() with veritesting=True to skip through the input function automatically',
                    'Hook get_user_input() with an empty SimProcedure that returns immediately'),
                _mc('c1_q7',
                    'Q7. After successful exploration, why can you not simply print the symbolic variable password0 directly to get the solution?',
                    'Symbolic variables are not Python objects and cannot be passed to print()',
                    'password0 is a symbolic object representing potentially many values; you must call solver.eval() to find a concrete value consistent with all constraints accumulated during exploration',
                    'print() only accepts bytes objects, so you must encode the variable first',
                    "The variable is stored in angr's internal memory and is inaccessible from Python"),
                _mc('c1_q8',
                    'Q8. A function check_equals is called 256 times in a binary, each call creating branching constraints that cause state explosion. What is the most scalable angr solution?',
                    'Call simulation.explore() with a very high step limit to wait out the explosion',
                    'Create a SimProcedure class with a run() method that performs the comparison symbolically, then use hook_symbol to replace every call to check_equals at once',
                    'Add a manual constraint after each of the 256 calls using a loop in the scaffold script',
                    'Use blank_state() to start execution after all 256 calls have already executed'),
                _mc('c1_q9',
                    'Q9. In 04_angr_symbolic_stack, password0 is at ebp-0xc and password1 is at ebp-0x10. You set %ebp and %esp to the same location, then push symbols. Which push order is correct and why?',
                    'Push password1 first, then password0 — alphabetical order is required by angr',
                    'Push password0 first, then password1 — the stack grows downward, so pushing password0 first places it at a higher address (ebp-0xc) and password1 ends up at the lower address (ebp-0x10), matching the variable layout',
                    'The order does not matter as long as you set the correct register values afterward',
                    'Push password1 first — the last push always lands at the lower offset from ebp'),
                _mc('c1_q10',
                    'Q10. Veritesting helps with the 12_angr_veritesting challenge but is not needed for most earlier challenges. What specific program structure makes veritesting beneficial in that challenge?',
                    'The binary uses a shared library that angr cannot follow without state merging',
                    'A loop runs 32 times checking each character of the buffer, creating up to 2^32 states with standard exploration; veritesting merges states that pass through the same loop body, collapsing the explosion',
                    'The binary is statically linked, requiring veritesting to reconstruct libc calls',
                    'The scanf call uses multiple format specifiers that angr cannot handle without merging'),
                _heading('Part II — Short Answer  (Questions 11–12) — Answer in your own words, 3–5 sentences.'),
                _sa('c1_q11',
                    'Q11. A binary applies three transformations to user input (subtract 3, add 15, multiply by 7) before checking the result. Explain how constraint propagation allows angr to work backwards from the desired output to find the correct input, without running the binary with every possible value.'),
                _sa('c1_q12',
                    "Q12. You are analyzing a binary that prints 'WELCOME ADMIN' anywhere in a 200-byte output string mixed with other text. Explain why a raw address is insufficient as a find condition here, and write out (in pseudocode or Python) the is_successful function you would use instead."),
            ],
        },
    ],
}

# ---------------------------------------------------------------------------
# Combined lookup
# ---------------------------------------------------------------------------

SURVEY_LIST = [PRE_STUDY] + CHALLENGES + [POST_STUDY]
SURVEYS = {s['id']: s for s in SURVEY_LIST}
